//! Test fixtures generated by the existing independent Python native codecs.
use super::*;
use crate::live_jobs::LiveJobObservation;
use crate::live_operations::{LiveBuilding, LiveItem, OperationsProfile};
use dfmcp_core::{
    CapabilityGrant, CapabilityScope, MapCoord, ObservationCursor, RequestId, SessionId,
    StateAnchor, WorkBudget,
};

pub(crate) const TICK: u64 = 806_500;
pub(crate) fn hex(raw: &str) -> Vec<u8> {
    let raw = raw.trim();
    assert_eq!(raw.len() % 2, 0);
    raw.as_bytes()
        .chunks_exact(2)
        .map(|pair| {
            let value = std::str::from_utf8(pair).unwrap();
            u8::from_str_radix(value, 16).unwrap()
        })
        .collect()
}
pub(crate) fn goal(count: usize) -> Goal {
    let original = Goal::decode(&hex(include_str!("testdata/python_goal_32.hex"))).unwrap();
    Goal::new(original.records()[..count].to_vec(), original.timing()).unwrap()
}
pub(crate) fn context(goal: &Goal) -> OperationContext {
    let before = goal.records()[0].plan().before();
    OperationContext {
        session_id: SessionId::new(711),
        request_id: RequestId::new(1),
        anchor: StateAnchor {
            fortress_id: before.fortress_id(),
            cursor: ObservationCursor::ORIGIN,
            tick: GameTick(before.tick()),
            state_hash: before.witness(),
        },
        budget: WorkBudget {
            max_wall_millis: 60_000,
            max_entities: 80_000,
            max_bytes: 64 * 1024 * 1024,
            ..WorkBudget::CONSERVATIVE_DEFAULT
        },
        grants: vec![CapabilityGrant {
            capability: Capability::Query,
            max_risk: RiskTier::ReadOnly,
            scope: CapabilityScope {
                fortress_id: Some(before.fortress_id()),
                ..CapabilityScope::default()
            },
            expires_at_tick: None,
            remaining_uses: None,
        }],
        cancellation_requested: false,
    }
}
pub(crate) fn observation(goal: &Goal, tick: u64) -> LiveOperationsObservation {
    let first = goal.records()[0].plan().before();
    let mut observed = LiveOperationsObservation {
        jobs: LiveJobObservation {
            bridge_generation: 987,
            df_version: "test-df".into(),
            dfhack_version: "test-dfhack".into(),
            year: (tick / 403_200) as u32,
            year_tick: (tick % 403_200) as u32,
            paused: true,
            site_id: first.site() as i32,
            world_folder: first.folder().to_owned(),
            next_job_id: 0,
            jobs: Vec::new(),
        },
        next_building_id: 0,
        next_item_id: 0,
        buildings: Vec::new(),
        items: Vec::new(),
        attachments: Vec::new(),
    };
    for record in goal.records() {
        let p = record.insertion().unwrap();
        let BuildItem::Visible(expected) = record.plan().before().item() else {
            panic!("fixture item");
        };
        let after = record.after().unwrap();
        let [x, y, z] = p.position().map(|n| n as i32);
        let (kind, item_kind) = match p.kind() {
            BuildKind::Bed => ("Bed", "BED"),
            BuildKind::Chair => ("Chair", "CHAIR"),
            BuildKind::Table => ("Table", "TABLE"),
        };
        observed.jobs.next_job_id = observed.jobs.next_job_id.max(after.next_job_id());
        observed.next_building_id = observed.next_building_id.max(after.next_building_id());
        observed.next_item_id = observed.next_item_id.max(p.item_id() + 1);
        observed.buildings.push(LiveBuilding {
            native_id: p.building_id(),
            building_type: p.kind() as i32,
            type_key: kind.into(),
            x1: x,
            y1: y,
            x2: x,
            y2: y,
            z,
            build_stage: p.max_stage() as i32,
            max_build_stage: p.max_stage() as i32,
        });
        observed.items.push(LiveItem {
            native_id: p.item_id(),
            item_type: expected.native_type() as i32,
            type_key: item_kind.into(),
            subtype: expected.subtype(),
            material_type: expected.material(),
            material_index: expected.material_index(),
            stack_size: 1,
            raw_position: MapCoord::new(15, 15, 2),
            flags: 256,
            container_native_id: None,
            holder_building_native_id: Some(p.building_id()),
        });
    }
    observed.items.sort_by_key(|item| item.native_id);
    observed
}
pub(crate) fn sample(goal: &Goal, tick: u64) -> LinkedSample {
    with_observation(goal, observation(goal, tick))
}
pub(crate) fn with_observation(goal: &Goal, observed: LiveOperationsObservation) -> LinkedSample {
    let before = Manifest {
        generation: goal.records()[0].plan().before().generation(),
        df_version: observed.jobs.df_version.clone(),
        dfhack_version: observed.jobs.dfhack_version.clone(),
    };
    let records = goal
        .records()
        .iter()
        .map(|record| record.canonical_bytes().to_vec())
        .collect::<Vec<_>>();
    LinkedSample {
        before: before.clone(),
        before_records: records.clone(),
        operations: Manifest {
            generation: observed.jobs.bridge_generation,
            df_version: observed.jobs.df_version.clone(),
            dfhack_version: observed.jobs.dfhack_version.clone(),
        },
        capture: observed
            .encode_profile(OperationsProfile::PagedV1_4)
            .unwrap(),
        after: before,
        after_records: records,
    }
}
